import Head from 'next/head'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>s759Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-screen flex-col">
        <h1 className="text-9xl flex">
          Welcome to&nbsp;
        </h1>

        <p className="flex">
          This is a sample page of s759labs LLc.
        </p>

      </main>
      <main className="flex justify-center items-center h-screen flex-col bg-black text-white">
        <h1 className="text-9xl flex">
          Welcome to&nbsp;<a className="font-bold" href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="flex">
          Get started by editing{' '}
          <code >pages/index.js</code>
        </p>

      </main>

    </div>
  )
}
