import React, {useEffect, useState} from 'react';
import TabCard from "./TabCard";
import Image from "next/image";
import PropTypes from "prop-types";
import constants from "../../../Constants/Constants";

const disabled = true;
const OtherPlatformTab = ({pageInfo}) => {

  const [selectedData, setSelectedData] = useState([]);

  useEffect(() => {
    if (pageInfo) {
      const array = rawData.filter((row) => row.label !== pageInfo);
      setSelectedData(array.sort(() => Math.random() - Math.random()).slice(0, 3));
    }
  }, [pageInfo]);

  if(disabled){
    return <></>
  }

  return (
    <div className="mt-28 ml-2 mr-2 sm:ml-8 sm:mr-8 flex justify-center items-center relative">
      <div className="flex justify-center items-stretch flex-wrap">
        {
          selectedData?.map((item) => (<TabCard key={item.id} {...item} />))
        }
      </div>
      <div className="absolute -bottom-72 -left-12 -z-10">
        <Image src="/images/dottedSkillCounty.png" width="500px" height="500px"/>
      </div>
    </div>
  );
};

export default OtherPlatformTab;

OtherPlatformTab.propTypes = {
  pageInfo: PropTypes.string
}

const rawData = [
  {
    id: 1,
    label: constants.customAssessments,
    description: "Create an assessment from the ground up using a wide variety of question types and that contains questions from both your experts and our experts\n",
    route: "/platform/custom-assessments"
  },
  {
    id: 2,
    label: constants.oneWayInterviewsOrAsynchronousInterviews,
    description: "No need to scan schedules for a common slot and cast a wider net and truly assess these skills in the early stages of the hiring process.",
    route: "/platform/one-way-interviews"
  },
  {
    id: 3,
    label: constants.codingAssessmentsAndInterviews,
    description: "Conduct coding assessments, hackathons, remote coding interviews and remote design interviews. You can assess technical skills along with important soft skills.\n",
    route: "/platform/coding-assessments"
  },
  {
    id: 4,
    label: constants.AIBasedEvaluations,
    description: "Assessment report is generated by an AI based algorithm that auto-grades candidates’ answers to both objective and subjective questions enabling easier hiring processes and workflows.\n",
    route: "/platform/ai-based-evaluations"
  },
  {
    id: 5,
    label: constants.proctoring,
    description: "Ensure integrity of the assessment by tracking & recording candidate activity and setting up a controlled test environment.\n",
    route: "/platform/proctoring"
  },
  {
    id: 6,
    label: constants.questionLibrary,
    description: "Library offers hundreds of questions that cover a wide range of skills & roles or you can develop your own pool of questions as well.\n",
    route: "/platform/question-library"
  },
  {
    id: 7,
    label: constants.assessmentMarketPlace,
    description: "Offers a number of pre-made assessments for a variety of roles thus it takes less than 2 mins to start your hiring process.\n",
    route: "/platform/assessment-marketplace"
  },
  {
    id: 8,
    label: constants.psychometricAssessments,
    description: "SkillCounty offers assessments to gauge the extent to which your candidates' expectations align with your job offer and how a candidate’s values and behaviors align with your company’s. ",
    route: "/platform/psychometric-assessments"
  }
]

